### ISSUE TITLE
2017-1-21 第一周周报 周报

### ISSUE THREAD

**Issue by heXiangpeng** [icsnju/X#17]
王惟一

本周工作

跑实验和修改论文，在和 @ying-zhang 讨论之后，再做如下修改

突出复合主键，但是要考虑是否支持第三列扩展。
取消region size，因为一旦设置了region size就无法应对数据增长的情况，并且用region size来代表应用有些牵强。但是取消region size之后如何确定各个参数是一个问题，目前的想法是先跑实验看看各个方案之间有什么差异，例如440个CF，分成10张表，20张表还是1张表。以及初始的时候pre-split多少个region。
找到一个卖点：本模型可以减少磁盘存储。
多表存储虽然不会占用额外的rowkey存储，但是有没有必要这样做？还是只考虑一张表以及压缩存储CF的情况。
下周工作

解决以上问题
看SpringSecurity和JAAS
想说的话

感谢营长

**Comment by co2y** [comment]
这个issue是要干嘛
